=begin
gui_config.rb
Copyright (c) 2007-2023 University of British Columbia

GUI configuration options, mostly takes data from RecallConfig
=end
require 'lib/recall_config'

class GuiConfig < Hash
  def initialize
    @user = RecallConfig.user_context

    self['editor_bw']=RecallConfig['guiconfig.editor_bw'] == 'true' ? true : false
    self['show_standard']=RecallConfig['guiconfig.show_standard'] == 'true' ? true : false
    self['show_amino']=RecallConfig['guiconfig.show_amino'] == 'true' ? true : false
    self['show_primermap']=RecallConfig['guiconfig.show_primermap'] == 'true' ? true : false
    self['win_height']=RecallConfig['guiconfig.win_height'].to_i
    self['win_width']=RecallConfig['guiconfig.win_width'].to_i
    self['win_maximized']=RecallConfig['guiconfig.win_maximized'] == 'true' ? true : false
    self['h_stretch']=RecallConfig['guiconfig.h_stretch'].to_f
    self['w_stretch']=RecallConfig['guiconfig.w_stretch'].to_f
    self['export_dir']=RecallConfig['guiconfig.export_dir'].to_s
    self['clinical']=RecallConfig['guiconfig.clinical'].to_s
    self['sh_dir']=RecallConfig['guiconfig.sh_dir'].to_s
    self['background_colour']=RecallConfig['guiconfig.background_colour'].split(',').map{|a| a.to_f}
  end

  def save
    #Read the file.
    text = ''
    begin
    File.open("#{RecallConfig.dir}user_#{@user}.txt") do |file|
      file.each_line do |line|
        text += line if(! (line =~ /guiconfig\./) and !(line =~ /^#/) and line.strip != '')
      end
    end
    rescue

    end

    #write all GuiConfig entries.
    File.open("#{RecallConfig.dir}user_#{@user}.txt", 'w') do |file|
      file.puts text
      file.puts
      file.puts "#The following lines are autogenerated"
      file.puts
      file.puts 'guiconfig.editor_bw=' + self['editor_bw'].to_s
      file.puts 'guiconfig.show_standard=' + self['show_standard'].to_s
      file.puts 'guiconfig.show_amino=' + self['show_amino'].to_s
      file.puts 'guiconfig.show_primermap=' + self['show_primermap'].to_s
      file.puts 'guiconfig.win_height=' + self['win_height'].to_s
      file.puts 'guiconfig.win_width=' + self['win_width'].to_s
      file.puts 'guiconfig.win_maximized=' + self['win_maximized'].to_s
      file.puts 'guiconfig.h_stretch=' + self['h_stretch'].to_s
      file.puts 'guiconfig.w_stretch=' + self['w_stretch'].to_s
      file.puts 'guiconfig.export_dir=' + self['export_dir'].to_s
      file.puts 'guiconfig.clinical=' + self['clinical'].to_s
      file.puts 'guiconfig.sh_dir=' + self['sh_dir'].to_s
      file.puts 'guiconfig.background_colour=' + self['background_colour'].map{|a| a.to_s}.join(',')
      file.puts
    end
    RecallConfig.reload()
  end

end
